version: "3.9"

services:
  vote:
    image: vote:latest
    build: ./vote
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - front
      - back

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
    networks:
      - back

  worker:
    image: worker:latest
    build: ./worker
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - back

  result:
    image: result:latest
    build: ./result
    ports:
      - target: 80
        published: 5001
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - front
      - back

networks:
  front:
    driver: overlay
  back:
    driver: overlay

volumes:
  db_data:
