name: CI/CD for Voting App

on:
  push:
    branches:
      - main  # ya aapki default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker images
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vote:latest ./vote --target final
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worker:latest ./worker --target final
          docker build -t ${{ secrets.DOCKER_USERNAME }}/result:latest ./result --target final

      # 4. Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vote:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/worker:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/result:latest

      # 5. SSH to EC2 and update Docker Swarm
      - name: Update Swarm on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/vote:latest votingapp_vote
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/worker:latest votingapp_worker
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/result:latest votingapp_result
